name: Built and test PRs

on:
  pull_request:
    
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APP_NAME: ${{ secrets.APP_NAME }}
  REGION: us-west1

jobs:
    checks:
        name: Build and test PR
        runs-on: ubuntu-latest
        environment: testing

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Node
            uses: actions/setup-node@v4

          - name: Install dependencies
            run: npm install

          - name: Build
            run: npm run build

          - name: Run frontend tests
            run: npm test
          
          - name: Build the Docker image
            run: |
                set -e
                echo "Building Docker image."
                docker build -t pmc-portal-fe:${{ github.event.pull_request.number }} .
                echo "Docker image successfully created."
            
          - name: Verify Docker image
            run: |
                set -e
                echo "Verifying Docker image exists..."    
                docker images pmc-portal-fe:${{ github.event.pull_request.number }}
                echo "Docker image verified."

          - name: Remove Docker image
            run: |
                set -e
                echo "Deleting Docker image..."
                docker rmi pmc-portal-fe:${{ github.event.pull_request.number }}
                echo "Docker image deleted."
            
