name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APP_NAME: ${{ secrets.APP_NAME }}
  REGION: us-west1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .secret folder
        run: mkdir .secret

      - name: Create env file
        run: |
          touch .secret/.env
          echo ${{ secrets.ENV }} >> .secret/.env

      - name: Create Credential JSON
        id: create-json-1
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "firebase-config.json"
          json: ${{ secrets.FIREBASE_CONFIG }}
          dir: ".secret/"

      - name: Log into Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Run Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}

      - name: Deploy to Cloud Run
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud run deploy ${{ env.APP_NAME }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }} --region ${{ env.REGION }} --allow-unauthenticated
